name: 'InspectCode'
author: 'Nick Badal'
description: 'An action that runs the InspectCode utility from JetBrains'
inputs:
    solution:
        description: 'Filename of your solution, ex: MyProject.sln'
        required: true
    include:
        description: 'Relative path(s) or wildcards that define the files to include during the inspection'
        required: false
    exclude:
        description: 'Relative path(s) or wildcards that define the files to exclude during the inspection. Include takes higher priority'
        required: false
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.solution }}