name: 'Resharper InspectCode'
author: 'Nick Badal'
description: 'An action that runs the InspectCode CLI utility from JetBrains'
inputs:
    solution:
        description: 'Path to your solution file, ex: MyProject.sln'
        required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.solution }}
        - '-o=report.xml'