name: SelfTest

on:
  push:
    branches: [ master ]

jobs:
  self-test:
   runs-on: windows-latest
   name: Self Test
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Test
       uses: ./ # Uses the action in the root directory
       id: test
       with:
          solution: './TestSolution/TestSolution.sln'
     - name: Upload
       uses: actions/upload-artifact@v1
       with:
         name: inspection.xml
         path: inspection.xml
